highlighter: pygments
permalink: pretty
markdown: kramdown

title: Lecture
description: "Lecture theme inspired from newvim"

news:
    name: Lecture News
    authors: lecture news
    url: http://kwangkim.github.io/lecture/news
    feed: /news.xml

url: "http://kwangkim.github.io/lecture"
basepath : "/lecture"

gems:
    - jekyll-redirect-from
    - jekyll-mentions

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
